
services:
  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  backend:
    build: .
    command: bash -c 'python ./backend/manage.py migrate && python ./backend/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db